---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install basic dependencies
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - software-properties-common
      - gnupg2
    state: present
