---
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Gather installed package facts
  package_facts:
    manager: apt

- name: Install PHP 8.2 and required extensions if not already installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php8.2
    - php8.2-fpm
    - php8.2-curl
    - php8.2-dom
    - php8.2-fileinfo
    - php8.2-gd
    - php8.2-iconv
    - php8.2-intl
    - php8.2-mbstring
    - php8.2-mysql  # Corrected name for the MySQL extension
    - php8.2-phar
    - php8.2-simplexml
    - php8.2-xml
    - php8.2-zip
    - php8.2-cli
    - php8.2-bcmath
    - php8.2-soap
  when: "'{{ item }}' not in ansible_facts.packages"

- name: Restart PHP-FPM Service using service command
  command: service php8.2-fpm restart
  ignore_errors: yes  # Avoid failure if the service is already running or if there's an issue
