---
- name: Install Composer globally
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php

- name: Run Composer installer
  command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer

- name: Create web root directory for Shopware
  file:
    path: /var/www/shopware
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Install Shopware 6.5.8.7 via Composer
  command: composer create-project shopware/production:6.5.8.7 /var/www/shopware --no-interaction
  become: true
  become_user: www-data

- name: Set permissions on Shopware directory
  file:
    path: /var/www/shopware
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

